### PR TITLE
Add ducc FFT

### PR DESCRIPTION
**Pull request by mreineck**
This is a first attempt. I'm not sure I've thought of everything ... the library can be benchmarked for multi-D transforms and support multi-threading.

### CODE REVIEW

**Comment by blackwer** [comment]
Looks good to me. I've added openmp support locally. I'll go ahead and merge this and apply my patches on main
Thanks! Hopefully we'll pull this into finufft :)

**Comment by mreineck** [comment]
Thanks!

Completely independent of the actual FFT implementation, I have a few ideas how to improve the speed of the FFTs in finufft:
- assuming you transform an array of size `(nx,ny,nz)`, where `nz` is a large power of 2, the FFT along the first and second axes will be unnecessarily slow because of memory accesses with critical stride. This can be avoided by padding the last axis by a few entries (without enlarging the user-visible size), and it can give very significant speedups.
- in 2D and 3D NUFFTs, especially when using the oversampling factor of 2, FFTs do not have to be carried out over the entire array along all directions; some of these would operate on parts of the array that are known to be uniformly zero, and some others would produce parts of the array which are known not to be read later on. In 2D with an oversampling of 2, this nominally saves 25% of FFT time, in 3D it is even more.

But I'm getting off-opic now :)

**Comment by mreineck** [comment]
"CPU" timings with OpenMP look completely off, normal "Time" seems OK. That's probably because ducc uses its own thread pool for parallelization instead of OpenMP.

**Comment by mreineck** [comment]
One small remark concerning the multithreaded benchmarks: it seems that OpenMP threads and Posix threads interfere badly with each other when running the benchmark with the standard setup. I'm currently using 

```bash
export OMP_WAIT_POLICY=passive
unset OMP_PROC_BIND
unset OMP_PLACES
$FFT_BENCH_PATH/ducc_omp_bench --benchmark_out=ducc-omp-marvin.json --benchmark_out_format=json --benchmark_time_unit=us
```

This gives more or less the results I expect.

**Comment by blackwer** [comment]
> This gives more or less the results I expect.

I've published results to the main README given this suggestion. Does this look good to you? Seems like ducc really shines in AVX2 environments, though it also might be an Intel vs AMD thing. I'll try to get some `genoa` benchmarks soon, which should clear that up a bit.

**Comment by mreineck** [comment]
Thanks!

Yes, that looks pretty much as expected. The goal with `ducc` is to be good at large, multi-D transforms. There has not been much effort to parallelize (or even vectorize) 1D transforms, which is why the parallel 1D plots look really terrible.

AVX2 is probably (comparatively) good since I'm mostly working and benchmarking on AMD and don't really have access to AVX512 hardware. AVX512 is in principle supported, but I've never tuned for it.

I really wonder why Intel is hobbling MKL FFT on AMD hardware ... they have given up on this behavior in most other parts of MKL some time ago.

**Comment by blackwer** [comment]
> Yes, that looks pretty much as expected. The goal with `ducc` is to be good at large, multi-D transforms. There has not been much effort to parallelize (or even vectorize) 1D transforms, which is why the parallel 1D plots look really terrible.

Is this something you'd be interested in improving?  Would be nice to have an alternative to MKL in this arena. I could offer some assistance if there's serious interest.

> AVX2 is probably (comparatively) good since I'm mostly working and benchmarking on AMD and don't really have access to AVX512 hardware. AVX512 is in principle supported, but I've never tuned for it.

I've got no shortage here :). See above.

> I really wonder why Intel is hobbling MKL FFT on AMD hardware ... they have given up on this behavior in most other parts of MKL some time ago.

They likely only responded due to the bad press. No one was complaining about FFTs. Mostly just BLAS ops.

**Comment by mreineck** [comment]
> Is this something you'd be interested in improving? Would be nice to have an alternative to MKL in this arena. I could offer some assistance if there's serious interest.

It is certainly tempting, and whenever I have some time I look into this. But ultimately I fear that the return on investment is really bad in that area. To make 1D work well, we'd probably need support for length 16/32/64 passes, which are huge lumps of straight-line code (usually machine generated and fairly sensitive to details of the hardware thay are running on). My expectation is that we'd end up with a very large code base (probably an order of magnitude higher than the roughly 5k LOC for complex FFTs we have now) that requires a ot of maintenance to keep up to date.

Also, I'm not sure whether this kind of exercise would be helpful for many users ... how many codes are there with a bottleneck consisting of small to mid-sized FFTs, or long 1D FFTs?  Sure, there's a need for fixed-size very small FFTs (e.g. the DCTs in JPEG encoding), but those packages will use hand-crafted optimal implementations anyway.

So personally I'm happy to integrate any "low-hanging fruit" I encounter, but I'm not focused on getting the last bit of performance out of the library in areas where I don't see a clear need for it.
That's just my take however, and I'd love to see other people experimenting with and extending the code! (Unfortunately, the 1D FFT part is the messiest part of the library at the moment, sorry for that...)

**Pull request merged**
